# version: '3.8'

services:
  db:
    image: postgres:13.7-alpine
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=password
      #- TZ=Europe/Moscow

  server:
    build: ./server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - DB_NAME=shareit
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=6541
      #- TZ=Europe/Moscow

  gateway:
    build: ./gateway
    depends_on:
      - server
    ports:
      - "8080:8080"
    #environment:
      #- TZ=Europe/Moscow