# версия Docker Compose
# version: '3.8'

# имена и описания контейнеров, которые должны быть развёрнуты
services:
  # описание контейнера db
  db:
    # образ, из которого должен быть запущен контейнер
    image: postgres:13.7-alpine
    # volume и связанная с ним директория в контейнере
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=password
      - TZ=Europe/Moscow

  server:
    build: ./server
    ports:
      - "2020:2020"
    depends_on:
      - db
    environment:
      - DB_NAME=shareit
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=6541
      - TZ=Europe/Moscow

  gateway:
    build: ./gateway
    depends_on:
      - server
    ports:
      - "8080:8080"
    environment:
      - TZ=Europe/Moscow